name: SSH to Server and Run Git

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: false
        default: "staging"

  push:
    branches:
      - Release-v2.1.x

jobs:
  git-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Checkout del repositorio para obtener los cambios generados
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura las credenciales de Git
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add cicdtest https://github.com/juarezgonz02/mynewsite.git
          git config pull.rebase false

      # A침adir los archivos generados por el build
      # Usar el mensaje del commit que activ칩 el workflow
      # - name: Get production branch
      #   run: |
      #     git pull cicdtest production
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run production

      # A침adir los archivos generados por el build
      # Usar el mensaje del commit que activ칩 el workflow
      - name: Add and commit changes to production
        run: |
          git add .
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          git commit -m "$COMMIT_MSG"
          git status
          git checkout -b production cicdtest/production
          git checkout production   
          git status
          git merge Release-v2.1.x

      # Push a la rama 'production'
      # Realiza el push a la rama 'production' con el mismo mensaje
      - name: Push changes to production with the same commit message
        run: |
          git push cicdtest production

  ssh-to-server:
    runs-on: ubuntu-latest
    needs: git-node  # Fix this line to reference the correct job name
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up the SSH key
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # SSH into the server and run git log
      - name: SSH and run git log
        run: |
          ssh -o StrictHostKeyChecking=no juarez@jgdevtech.lat << 'EOF'
            cd /var/www/css-proyecto
            git checkout production
            echo "=== Pull Started at $(date) ===" >> pull_log.txt
            git pull origin production >> pull_log.txt 2>&1  # Append the result of the git pull
            echo "=== Pull end at $(date) ===" >> pull_log.txt
          EOF